theme: jekyll-theme-midnight
title: "FootPage"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Stories for people, by people"
google_analytics:
